project:
  name: quickstart-dotnetfx-ecs-cicd
  regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - eu-central-1
  - ap-southeast-1
  - ap-southeast-2
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  package_lambda: false
tests:
  default:
    template: ./templates/quickstart-dotnetfx-ecs-cicd-new-cluster.template.yaml
    parameters:
      EcsClusterName: "taskcat"
      EcsServiceName: "taskcat-service"
      TaskContainerName: "sampleapp"
      GitHubRepositoryName: "quickstart-dotnetfx-ecs-cicd"
      GitHubBranchName: "develop"
      GitHubOwner: override
      GitHubOAuthToken: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
